// frontend/src/components/Header.jsx
// frontend/src/components/Header.jsx
import React from 'react';

function Header({ title, description, children }) {
  return (
    <div className="p-6 bg-white border-b border-gray-200">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-800">
            {title}
          </h1>
          {description && (
            <p className="text-gray-600 mt-1">
              {description}
            </p>
          )}
        </div>
        {children && (
          <div className="flex items-center gap-3">
            {children}
          </div>
        )}
      </div>
    </div>
  );
}

export default Header;

// admin/src/components/header.vue
<template> 
  <!-- Left side - Page title -->
    <div class="flex flex-col items-center justify-center h-full text-center">
      <h1 class="text-2xl font-semibold text-gray-800">{{ pageTitle }}</h1>
    </div> 
</template>

<script setup>
const props = defineProps({
  pageTitle: {
    type: String,
    default: 'Dashboard'
  }
})
</script>
